version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: mycontainer
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vacancydb
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d vacancydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - spring-postgres-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  spring-postgres-network:
    driver: bridge